### PR TITLE
insert silly white space to make a change

### PR DESCRIPTION
**Pull request by yoachim**
Looks like the ephem package works, I was able .  Do I need to add any tags or versions to it?

### CODE REVIEW

**Comment by timj** [comment]
In DM you would have created a README in the new package and then added the tar file and `ups` directory on a ticket branch. I have no say over how things work in Sims but this pull request seems less than optimal 😄 I'll go and look at the master commit (but won't be able to comment on them in line). It is still possible for you to change the way you have done this PR so that you make it more obvious (just by changing where the branch sits in your history).

**Comment by timj** [comment]
Please add the README back. Do you need the cfg file? `ephem` is only going to be used from Python isn't it?

**Comment by yoachim** [comment]
I thought the README was the reason it wasn't able to build?

**Comment by timj** [comment]
But then you declared it was a tap package

**Pull request merged**
